version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: gateway-container
    ports:
      - "8080:8080"
    depends_on:
     - server
    environment:
    - SERVER_PORT=8080
    - SHAREIT_SERVER_URL=http://server:8090
    - TZ=Europe/Moscow

  server:
    build: server
    image: server-image
    container_name: server-container
    ports:
      - "8090:8090"
    depends_on:
      - server-db
    environment:
      - SERVER_PORT=8090
      - SHAREIT_GATEWAY_URL=http://gateway:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://server-db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - TZ=Europe/Moscow

  server-db:
    image: postgres:14-alpine
    container_name: server-container-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot
      - TZ=Europe/Moscow
